sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t yarlaghh/docker_react_learning -f Dockerfile.dev .

script:
  - docker run -e CI=true yarlaghh/docker_react_learning npm run test
